### ISSUE TITLE
crashing (possible memory leak)

### ISSUE THREAD

**Issue by cannotcode** [igrigorik/node-spdyproxy#50]
After using the proxy for some hours, it randomly stops processing new connections. Going through the log, I found errors like the following:  

```
(node) warning: possible EventEmitter memory leak detected. 101 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at ServerResponse.addListener (events.js:160:15)
    at ServerResponse.once (events.js:185:8)
    at IncomingMessage.Readable.pipe (_stream_readable.js:538:8)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/spdyproxy/lib/server.js:80:12)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1688:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at Socket.socketOnData [as ondata] (http.js:1583:20)
    at TCP.onread (net.js:527:27)
```

any tips? thanks in advance

**Comment by sunyc** [comment]
I had a similar issue with memory usage growing to over 1G in a couple hours.

I'm now trying to use the HEAD version to see if it is solved.  

But in general , how to debug this?
