### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor" argument must be of type Function. Received type undefined?

### ISSUE THREAD

**Issue by luckypoem** [igrigorik/node-spdyproxy#68]
hi.

root@wh:~# spdyproxy -k /root/private.key -c /root/public.crt -p 344 -U myusername -P mypassword

the command shows:
util.js:281
    throw new ERR_INVALID_ARG_TYPE('superCtor', 'Function', superCtor);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor" argument must be of type Function. Received type undefined
    at Object.inherits (util.js:281:11)
    at Object.<anonymous> (/root/node-v10.14.1-linux-x64/lib/node_modules/spdyproxy/node_modules/spdy/lib/spdy/connection.js:84:6)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/root/node-v10.14.1-linux-x64/lib/node_modules/spdyproxy/node_modules/spdy/lib/spdy.js:20:19)
root@wh:~#

how to fix it?
thank u for ur reply!!

**Comment by luckypoem** [comment]
now i know how to fix it.
install nodejs v4.1.0
